name: "Transform OpenAPI to Postman Collection (from File)"
description: "Transforms an OpenAPI schema from a file into a Postman Collection."
inputs:
  openapi_schema_path:
    description: "The file path of the OpenAPI schema"
    required: true
    type: string
  output_file:
    description: "Optional output file if you want to a file rather than string output"
    required: true
    type: string
runs:
  using: "node16"
  main: "index.js"